# Generated by Django 2.2.4 on 2019-08-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('out_room_ID', models.IntegerField(default=0)),
                ('room_name', models.CharField(max_length=20)),
                ('room_owner', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=20)),
                ('game_state', models.IntegerField(default=0, null=True)),
                ('map_size', models.IntegerField(default=0, null=True)),
                ('game_info', models.CharField(max_length=100000)),
                ('map_setting', models.CharField(default='geneal', max_length=10000)),
                ('map_info', models.CharField(default='geneal', max_length=10000)),
                ('member_num', models.IntegerField(default=0, null=True)),
                ('member_max', models.IntegerField(default=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=20)),
                ('linking', models.IntegerField(default=0, null=True)),
                ('in_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='game.Room')),
            ],
        ),
    ]
