# Generated by Django 2.2.3 on 2019-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
